apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mock2
spec:
  hosts:
  - mock2-http1
  http:
  - route:
    - destination:
        host: mock2-http1.soa-test.svc.cluster.local
        port:
          number: 6000
    fault:
      abort:
        percent: 50
        httpStatus: 400

---
apiVersion: "networking.istio.io/v1alpha3"
kind: DestinationRule
metadata:
  name: mock2
spec:
  host: "mock2-http1.soa-test.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

