# Default values for mockserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
enableAuthn: true

image:
  repository: boscoellision/mockserver
  tag: v3.1
  pullPolicy: IfNotPresent

applications:
- name: mock1
  versions: ["v1", "v2"]
  errorRatios: [-1, -1]
  latencies: [5, 30]
  serviceType: "ClusterIP"
  redisAddr: "redis:6379"
  http1targetAuthn: "GET|http://mock2-authn.od-system:17001,POST|http://mock2-authn.od-system:17001"
  http1target: "GET|http://mock2-http1.od-system:6000,POST|http://mock2-http1.od-system:6000"
  http2target: "mock2-http2.od-system:6001"

- name: mock2
  versions: ["v1", "v2"]
  errorRatios: [-1, -1]
  latencies: [5, 10]
  serviceType: "ClusterIP"
  redisAddr: "redis:6379"
  http1targetAuthn: "GET|http://mock3-authn.od-system:17001,POST|http://mock3-authn.od-system:17001"
  http1target: "GET|http://mock3-http1.od-system:6000,POST|http://mock3-http1.od-system:6000"
  http2target: "mock4-http2.od-system:6001"

- name: mock3
  versions: ["v1", "v2", "v3"]
  errorRatios: [-1, -1, -1]
  latencies: [5, 3000, 5]
  serviceType: "ClusterIP"
  redisAddr: "redis:6379"
  http1targetAuthn: "GET|http://mock4-authn.od-system:17001"
  http1target: "GET|http://mock4-http1.od-system:6000"

- name: mock4
  versions: ["v1", "v2", "v3"]
  errorRatios: [-1, -1, -1]
  latencies: [5, 100, 5]
  serviceType: "ClusterIP"
  http1target: "GET|http://www.example.com"
