# Default values for mockserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: boscoellision/mockserver
  tag: latest
  pullPolicy: IfNotPresent

applications:
- name: mock1
  version: v1
  serviceType: "ClusterIP"
  redisAddr: "mockserver-redis-ha-master-svc:6379"
  redisSentinelAddrs: "mockserver-redis-ha-sentinel:26379"
  http1target: "http://mock2.soa-test:6000"
  http2target: "http://mock3.soa-test:6001"
  ports:
  - name: "http"
    port: "6000"
    protocal: "TCP"
  - name: "http2"
    port: "6001"
    protocal: "TCP"

- name: mock2
  version: v1
  serviceType: "ClusterIP"
  redisAddr: "mockserver-redis-ha-master-svc:6379"
  redisSentinelAddrs: "mockserver-redis-ha-sentinel:26379"
  http1target: "http://mock4.soa-test:6000"
  http2target: "http://mock4.soa-test:6001"
  ports:
  - name: "http"
    port: "6000"
    protocal: "TCP"
  - name: "http2"
    port: "6001"
    protocal: "TCP"

- name: mock3
  version: v1
  serviceType: "ClusterIP"
  redisAddr: "mockserver-redis-ha-master-svc:6379"
  redisSentinelAddrs: "mockserver-redis-ha-sentinel:26379"
  http1target: "http://mock4.soa-test:6000"
  http2target: "http://mock4.soa-test:6001"
  ports:
  - name: "http"
    port: "6000"
    protocal: "TCP"
  - name: "http2"
    port: "6001"
    protocal: "TCP"

- name: mock4
  version: v1
  serviceType: "ClusterIP"
  redisAddr: "mockserver-redis-ha-master-svc:6379"
  redisSentinelAddrs: "mockserver-redis-ha-sentinel:26379"
  ports:
  - name: "http"
    port: "6000"
    protocal: "TCP"
  - name: "http2"
    port: "6001"
    protocal: "TCP"
