# Default values for mockserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: boscoellision/mockserver
  tag: v3
  pullPolicy: IfNotPresent

applications:
- name: mock1
  version: v1
  serviceType: "ClusterIP"
  redisAddr: "redis:6379"
  http1target: "http://mock2-http1.soa-test:6000"
  http2target: "mock3-http2.soa-test:6001"
  errorRatio: -1

- name: mock2
  version: v1
  serviceType: "ClusterIP"
  redisAddr: "redis:6379"
  http1target: "http://mock4-http1.soa-test:6000"
  http2target: "mock4-http2.soa-test:6001"
  errorRatio: -1

- name: mock3
  version: v1
  serviceType: "ClusterIP"
  redisAddr: "redis:6379"
  http1target: "http://mock4-http1.soa-test:6000"
  http2target: "mock4-http2.soa-test:6001"
  errorRatio: -1

# - name: mock3v2
#   version: v2
#   serviceType: "ClusterIP"
#   redisAddr: "redis:6379"
#   http1target: "http://mock4-http1.soa-test:6000"
#   http2target: "mock4-http2.soa-test:6001"
#   errorRatio: -1

- name: mock4
  version: v1
  serviceType: "ClusterIP"
  redisAddr: "redis:6379"
  http1target: "http://mock5-http1.soa-test:6000"
  http2target: "mock5-http2.soa-test:6001"
  errorRatio: -1

# - name: mock4v2
#   version: v2
#   serviceType: "ClusterIP"
#   redisAddr: "redis:6379"
#   http1target: "http://mock5-http1.soa-test:6000"
#   http2target: "mock5-http2.soa-test:6001"
#   errorRatio: -1

- name: mock5
  version: v1
  serviceType: "ClusterIP"
  redisAddr: "redis:6379"
  http1target: "http://mock6-http1.soa-test:6000"
  http2target: "mock6-http2.soa-test:6001"
  errorRatio: -1

# - name: mock5v2
#   version: v2
#   serviceType: "ClusterIP"
#   redisAddr: "redis:6379"
#   http1target: "http://mock6-http1.soa-test:6000"
#   http2target: "mock6-http2.soa-test:6001"
#   errorRatio: -1

- name: mock6
  version: v1
  serviceType: "ClusterIP"
  redisAddr: "redis:6379"
  errorRatio: -1

# - name: mock6v2
#   version: v2
#   serviceType: "ClusterIP"
#   redisAddr: "redis:6379"
#   errorRatio: -1
