# Default values for mockserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: boscoellision/mockserver
  tag: v5
  pullPolicy: IfNotPresent

applications:
- name: mock1
  versions: ["v1"]
  errorRatios: [-1]
  serviceType: "ClusterIP"
  redisAddr: "redis:6379"
  http1target: "http://mock2-http1.soa-test:6000"
  http2target: "mock2-http2.soa-test:6001"

- name: mock2
  versions: ["v1", "v2"]
  errorRatios: [-1, 50]
  serviceType: "ClusterIP"
  redisAddr: "redis:6379"
