# Default values for mockserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: boscoellision/mockserver
  tag: latest
  pullPolicy: IfNotPresent

applications:
- name: mock1
  replicaCount: 3
  app: mock1
  version: v1
  serviceType: "ClusterIP"
  redisAddr: "mockserver-redis-ha-master-svc:6379"
  redisSentinelAddrs: "mockserver-redis-ha-sentinel:5000"
  ports:
  - name: "http1"
    port: "6000"
    protocal: "TCP"
  - name: "http2"
    port: "6001"
    protocal: "TCP"
