apiVersion: config.istio.io/v1alpha2
kind: prometheus
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"config.istio.io/v1alpha2","kind":"prometheus","metadata":{"annotations":{},"name":"handler","namespace":"istio-system"},"spec":{"metrics":[{"instance_name":"requestcount.metric.istio-system","kind":"COUNTER","label_names":["reporter","source_app","source_principal","source_workload","source_workload_namespace","source_version","destination_app","destination_principal","destination_workload","destination_workload_namespace","destination_version","destination_service","destination_service_name","destination_service_namespace","request_protocol","response_code","connection_security_policy"],"name":"requests_total"},{"buckets":{"explicit_buckets":{"bounds":[0.005,0.01,0.025,0.05,0.1,0.25,0.5,1,2.5,5,10]}},"instance_name":"requestduration.metric.istio-system","kind":"DISTRIBUTION","label_names":["reporter","source_app","source_principal","source_workload","source_workload_namespace","source_version","destination_app","destination_principal","destination_workload","destination_workload_namespace","destination_version","destination_service","destination_service_name","destination_service_namespace","request_protocol","response_code","connection_security_policy"],"name":"request_duration_seconds"},{"buckets":{"exponentialBuckets":{"growthFactor":10,"numFiniteBuckets":8,"scale":1}},"instance_name":"requestsize.metric.istio-system","kind":"DISTRIBUTION","label_names":["reporter","source_app","source_principal","source_workload","source_workload_namespace","source_version","destination_app","destination_principal","destination_workload","destination_workload_namespace","destination_version","destination_service","destination_service_name","destination_service_namespace","request_protocol","response_code","connection_security_policy"],"name":"request_bytes"},{"buckets":{"exponentialBuckets":{"growthFactor":10,"numFiniteBuckets":8,"scale":1}},"instance_name":"responsesize.metric.istio-system","kind":"DISTRIBUTION","label_names":["reporter","source_app","source_principal","source_workload","source_workload_namespace","source_version","destination_app","destination_principal","destination_workload","destination_workload_namespace","destination_version","destination_service","destination_service_name","destination_service_namespace","request_protocol","response_code","connection_security_policy"],"name":"response_bytes"},{"instance_name":"tcpbytesent.metric.istio-system","kind":"COUNTER","label_names":["reporter","source_app","source_principal","source_workload","source_workload_namespace","source_version","destination_app","destination_principal","destination_workload","destination_workload_namespace","destination_version","destination_service","destination_service_name","destination_service_namespace","connection_security_policy"],"name":"tcp_sent_bytes_total"},{"instance_name":"tcpbytereceived.metric.istio-system","kind":"COUNTER","label_names":["reporter","source_app","source_principal","source_workload","source_workload_namespace","source_version","destination_app","destination_principal","destination_workload","destination_workload_namespace","destination_version","destination_service","destination_service_name","destination_service_namespace","connection_security_policy"],"name":"tcp_received_bytes_total"}]}}
  clusterName: ""
  creationTimestamp: 2018-09-25T02:28:08Z
  generation: 1
  name: handler
  namespace: istio-system
  resourceVersion: "53781070"
  selfLink: /apis/config.istio.io/v1alpha2/namespaces/istio-system/prometheuses/handler
  uid: a423f993-c06a-11e8-b74f-0e3a25fe3428
spec:
  metrics:
  - instance_name: requestcount.metric.istio-system
    kind: COUNTER
    label_names:
    - reporter
    - source_app
    - source_principal
    - source_workload
    - source_workload_namespace
    - source_version
    - destination_app
    - destination_principal
    - destination_workload
    - destination_workload_namespace
    - destination_version
    - destination_service
    - destination_service_name
    - destination_service_namespace
    - request_protocol
    - response_code
    - connection_security_policy
    name: requests_total
  - buckets:
      explicit_buckets:
        bounds:
        - 0.005
        - 0.01
        - 0.025
        - 0.05
        - 0.1
        - 0.25
        - 0.5
        - 1
        - 2.5
        - 5
        - 10
    instance_name: requestduration.metric.istio-system
    kind: DISTRIBUTION
    label_names:
    - reporter
    - source_app
    - source_principal
    - source_workload
    - source_workload_namespace
    - source_version
    - destination_app
    - destination_principal
    - destination_workload
    - destination_workload_namespace
    - destination_version
    - destination_service
    - destination_service_name
    - destination_service_namespace
    - request_protocol
    - response_code
    - connection_security_policy
    name: request_duration_seconds
  - buckets:
      exponentialBuckets:
        growthFactor: 10
        numFiniteBuckets: 8
        scale: 1
    instance_name: requestsize.metric.istio-system
    kind: DISTRIBUTION
    label_names:
    - reporter
    - source_app
    - source_principal
    - source_workload
    - source_workload_namespace
    - source_version
    - destination_app
    - destination_principal
    - destination_workload
    - destination_workload_namespace
    - destination_version
    - destination_service
    - destination_service_name
    - destination_service_namespace
    - request_protocol
    - response_code
    - connection_security_policy
    name: request_bytes
  - buckets:
      exponentialBuckets:
        growthFactor: 10
        numFiniteBuckets: 8
        scale: 1
    instance_name: responsesize.metric.istio-system
    kind: DISTRIBUTION
    label_names:
    - reporter
    - source_app
    - source_principal
    - source_workload
    - source_workload_namespace
    - source_version
    - destination_app
    - destination_principal
    - destination_workload
    - destination_workload_namespace
    - destination_version
    - destination_service
    - destination_service_name
    - destination_service_namespace
    - request_protocol
    - response_code
    - connection_security_policy
    name: response_bytes
  - instance_name: tcpbytesent.metric.istio-system
    kind: COUNTER
    label_names:
    - reporter
    - source_app
    - source_principal
    - source_workload
    - source_workload_namespace
    - source_version
    - destination_app
    - destination_principal
    - destination_workload
    - destination_workload_namespace
    - destination_version
    - destination_service
    - destination_service_name
    - destination_service_namespace
    - connection_security_policy
    name: tcp_sent_bytes_total
  - instance_name: tcpbytereceived.metric.istio-system
    kind: COUNTER
    label_names:
    - reporter
    - source_app
    - source_principal
    - source_workload
    - source_workload_namespace
    - source_version
    - destination_app
    - destination_principal
    - destination_workload
    - destination_workload_namespace
    - destination_version
    - destination_service
    - destination_service_name
    - destination_service_namespace
    - connection_security_policy
    name: tcp_received_bytes_total
