{
 "title": "evangelist-init",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "source_app",
    "query": "label_values(istio_requests_total, source_app)"
   },
   {
    "name": "destination_app",
    "query": "label_values(istio_requests_total, destination_app)"
   }
  ]
 },
 "panels": [
  {
   "title": "Latency Stats - All",
   "type": "graph",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(istio_request_duration_seconds_bucket{source_app=~\"$source_app\", destination_app=~\"$destination_app\"}[30s])) by (le, source_app, source_version, destination_app, destination_version))",
     "legendFormat": "{{source_version}}.{{source_app}} -> {{destination_version}}.{{destination_app}}"
    }
   ]
  },
  {
   "title": "Traffic Stats - All",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{source_app=~\"$source_app\", destination_app=~\"$destination_app\"}[30s])) by (source_version, destination_version, source_app, destination_app)",
     "legendFormat": "{{source_version}}.{{source_app}} -> {{destination_version}}.{{destination_app}}"
    }
   ]
  },
  {
   "title": "Traffic Percentage - All",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{source_app=~\"$source_app\", destination_app=~\"$destination_app\"}[30s])) by (source_version, destination_version, source_app, destination_app)",
     "legendFormat": "{{source_version}}.{{source_app}} -> {{destination_version}}.{{destination_app}}"
    }
   ]
  },
  {
   "title": "Traffic Stats by Source",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{source_app=~\"$source_app\", destination_app=~\"$destination_app\"}[30s])) by (source_version, source_app)",
     "legendFormat": "{{source_version}}.{{source_app}} -> "
    }
   ]
  },
  {
   "title": "Traffic Percentage by Source",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{source_app=~\"$source_app\", destination_app=~\"$destination_app\"}[30s])) by (source_version, source_app)",
     "legendFormat": "{{source_version}}.{{source_app}} -> "
    }
   ]
  },
  {
   "title": "Traffic Stats - by Destination",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{source_app=~\"$source_app\", destination_app=~\"$destination_app\"}[30s])) by (destination_version, destination_app)",
     "legendFormat": "-> {{destination_version}}.{{destination_app}}"
    }
   ]
  },
  {
   "title": "Traffic Percentage - by Destination",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{source_app=~\"$source_app\", destination_app=~\"$destination_app\"}[30s])) by (destination_version, destination_app)",
     "legendFormat": "-> {{destination_version}}.{{destination_app}}"
    }
   ]
  }
 ]
}