kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: mymocks.config.istio.io
  labels:
    app: mixer
    package: mymock
    istio: mixer-adapter
spec:
  group: config.istio.io
  names:
    kind: mymock
    plural: mymocks
    singular: mymock
    categories:
    - istio-io
    - policy-istio-io
  scope: Namespaced
  version: v1alpha2

