apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: readonly-mock-all
spec:
  rules:
  - services:
    - "mock1-http1.soa-test.svc.cluster.local"
    - "mock2-http1.soa-test.svc.cluster.local"
    - "mock3-http1.soa-test.svc.cluster.local"
    - "mock4-http1.soa-test.svc.cluster.local"
    methods: ["GET"]

---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: readonly-mock-all
spec:
  subjects:
  - user: "*"
  roleRef:
    kind: ServiceRole
    name: "readonly-mock-all"
