apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: redis
spec:
  host: redis
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: redis
spec:
  hosts:
  - redis
  tcp:
  - route:
    - destination:
        host: redis.soa-test.svc.cluster.local
        port:
          number: 6379
