apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: redis
spec:
  host: redis
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: redis
spec:
  hosts:
  - redis
  tcp:
  - route:
    - destination:
        host: redis.soa-test.svc.cluster.local
        port:
          number: 6379

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mock1
spec:
  hosts:
  - "mock.example.info"
  gateways:
  - soa-gateway
  http:
  - route:
    - destination:
        host: mock1-http1.soa-test.svc.cluster.local
        port:
          number: 6000

---
apiVersion: "networking.istio.io/v1alpha3"
kind: DestinationRule
metadata:
  name: mock1
spec:
  host: "mock1-http1.soa-test.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

