apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: mock3-http1-post
spec:
  rules:
  - services: ["mock3-http1.soa-test.svc.cluster.local"]
    methods: ["POST"]

---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: mock3-http1-post
spec:
  subjects:
  # ServiceAccount name
  - user: "cluster.local/ns/soa-test/sa/mock2-v1"
  - user: "cluster.local/ns/soa-test/sa/mock2-v2"
  - user: "cluster.local/ns/soa-test/sa/mock2-v3"
  roleRef:
    kind: ServiceRole
    name: "mock3-http1-post"

---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: readonly-mock-all
spec:
  rules:
  - services:
    - "mock1-http1.soa-test.svc.cluster.local"
    - "mock2-http1.soa-test.svc.cluster.local"
    - "mock3-http1.soa-test.svc.cluster.local"
    - "mock4-http1.soa-test.svc.cluster.local"
    methods: ["GET"]

---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: readonly-mock-all
spec:
  subjects:
  - user: "*"
  roleRef:
    kind: ServiceRole
    name: "readonly-mock-all"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mock2-http1
spec:
  hosts:
  - mock2-http1
  tcp:
  - route:
    - destination:
        host: mock2-http1.soa-test.svc.cluster.local
        port:
          number: 6000

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mock2-http2
spec:
  hosts:
  - mock2-http2
  tcp:
  - route:
    - destination:
        host: mock2-http2.soa-test.svc.cluster.local
        port:
          number: 6001

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mock3-http1
spec:
  hosts:
  - mock3-http1
  tcp:
  - route:
    - destination:
        host: mock3-http1.soa-test.svc.cluster.local
        port:
          number: 6000

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mock3-http2
spec:
  hosts:
  - mock3-http2
  tcp:
  - route:
    - destination:
        host: mock3-http2.soa-test.svc.cluster.local
        port:
          number: 6001

---
apiVersion: "networking.istio.io/v1alpha3"
kind: DestinationRule
metadata:
  name: mock2-http1
spec:
  host: "mock2-http1.soa-test.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

---
apiVersion: "networking.istio.io/v1alpha3"
kind: DestinationRule
metadata:
  name: mock2-http2
spec:
  host: "mock2-http2.soa-test.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

---
apiVersion: "networking.istio.io/v1alpha3"
kind: DestinationRule
metadata:
  name: mock3-http1
spec:
  host: "mock3-http1.soa-test.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

---
apiVersion: "networking.istio.io/v1alpha3"
kind: DestinationRule
metadata:
  name: mock3-http2
spec:
  host: "mock3-http2.soa-test.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
