{
 "title": "evangelist-init",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "source_app",
    "query": "label_values(istio_requests_total, source_app)"
   },
   {
    "name": "destination_app",
    "query": "label_values(istio_requests_total, destination_app)"
   },
   {
    "name": "response_code",
    "query": "label_values(istio_requests_total, response_code)"
   },
   {
    "name": "source_version",
    "query": "label_values(istio_requests_total, source_version)"
   },
   {
    "name": "destination_version",
    "query": "label_values(istio_requests_total, destination_version)"
   },
   {
    "name": "evangelist_user",
    "query": "label_values(istio_myrequests_total, evangelist_user)"
   },
   {
    "name": "evangelist_user_group",
    "query": "label_values(istio_myrequests_total, evangelist_user_group)"
   }
  ]
 },
 "panels": [
  {
   "title": "Traffic Stats by User/Group",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_myrequests_total{source_app=~\"$source_app\", destination_app=~\"$destination_app\", source_version=~\"$source_version\", destination_version=~\"$destination_version\", response_code=~\"$response_code\", evangelist_user=~\"$evangelist_user\", evangelist_user_group=~\"$evangelist_user_group\"}[60s])) by (evangelist_user, evangelist_user_group)",
     "legendFormat": "{{evangelist_user}}({{evangelist_user_group}})"
    }
   ]
  },
  {
   "title": "Traffic Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{source_app=~\"$source_app\", destination_app=~\"$destination_app\", source_version=~\"$source_version\", destination_version=~\"$destination_version\", response_code=~\"$response_code\"}[30s])) by (source_version, destination_version, source_app, destination_app, response_code)",
     "legendFormat": "{{source_version}}.{{source_app}} -> {{destination_version}}.{{destination_app}}({{response_code}})"
    }
   ]
  },
  {
   "title": "Traffic Distribution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{source_app=~\"$source_app\", destination_app=~\"$destination_app\", source_version=~\"$source_version\", destination_version=~\"$destination_version\", response_code=~\"$response_code\"}[30s])) by (source_version, destination_version, source_app, destination_app, response_code)",
     "legendFormat": "{{source_version}}.{{source_app}} -> {{destination_version}}.{{destination_app}}({{response_code}})"
    }
   ]
  },
  {
   "title": "Traffic Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(istio_request_duration_seconds_bucket{source_app=~\"$source_app\", destination_app=~\"$destination_app\", source_version=~\"$source_version\", destination_version=~\"$destination_version\", response_code=~\"$response_code\"}[30s])) by (source_version, destination_version, source_app, destination_app, response_code, le))",
     "legendFormat": "{{source_version}}.{{source_app}} -> {{destination_version}}.{{destination_app}}({{response_code}})"
    }
   ]
  }
 ]
}