apiVersion: "config.istio.io/v1alpha2"
kind: memquota
metadata:
  name: handler
  namespace: istio-system
spec:
  quotas:
  - name: requestcount.quota.istio-system
    maxAmount: 30
    validDuration: 3s
    overrides:
    - dimensions:
        destination: mock1-http1
      maxAmount: 5
      validDuration: 3s
