apiVersion: "config.istio.io/v1alpha2"
kind: redisquota
metadata:
  name: handler
spec:
  redisServerUrl: redis.soa-test.svc:6379
  connectionPoolSize: 10
  quotas:
  - name: requestcount.quota.soa-test
    maxAmount: 200
    validDuration: 60s
    bucketDuration: 1s
    rateLimitAlgorithm: ROLLING_WINDOW
    overrides:
    - dimensions:
        destination: mock1-http1
        destinationVersion: v1
      # maxAmount must > 1
      maxAmount: 1
---
apiVersion: "config.istio.io/v1alpha2"
kind: quota
metadata:
  name: requestcount
spec:
  dimensions:
    source: request.headers["x-forwarded-for"] | "unknown"
    destination: destination.labels["app"] | destination.service | "unknown"
    destinationVersion: destination.labels["version"] | "unknown"

---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: quota
spec:
  actions:
  - handler: handler.redisquota
    instances:
    - requestcount.quota

---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpec
metadata:
  name: requestcount
spec:
  rules:
  - quotas:
    - charge: 1
      quota: requestcount

---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpecBinding
metadata:
  name: requestcount
spec:
  quotaSpecs:
  - name: requestcount
    namespace: soa-test
  services:
  - name: mock1-http1
    namespace: soa-test
