apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redis-admin
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redis-admin
subjects:
- kind: ServiceAccount
  name: rate-limit-redis-ha
  namespace: default
- kind: ServiceAccount
  name: default
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redis-admin
