apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mock1
spec:
  hosts:
    - 'mock1.soa-test.svc.cluster.local'
  http:
  - match:
    - uri:
        prefix: "/xxx"
      port: 6000
    route:
    - destination:
        host: mock1.soa-test.svc.cluster.local
        port:
          number: 6000

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mock-server
spec:
  host: mock1.soa-test.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
