apiVersion: "config.istio.io/v1alpha2"
kind: mymock
metadata:
  name: denyv23mockhandler
spec:
---
apiVersion: "config.istio.io/v1alpha2"
kind: checknothing
metadata:
  name: denyv23instance
spec:
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: denyv23rule
spec:
  match: request.headers["x-evangelist-myuser"] == "user1"
  actions:
  - handler: denyv23mockhandler.mymock
    instances: [ denyv23instance.checknothing ]
