apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-https
spec:
  hosts:
  - "www.google.com"
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: google
spec:
  gateways:
  - "google"
  hosts:
  - "www.google.com"
  tls:
  - match:
    - port: 443
      sni_hosts:
      - www.google.com
    route:
    - destination:
        host: www.google.com
        port:
          number: 443
      weight: 100

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: google
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "www.google.com"
    port:
      name: https
      number: 443
      protocol: TCP
    # tls:
    #   mode: SIMPLE
    #   serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
    #   privateKey: /etc/istio/ingressgateway-certs/tls.key

