apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: mypromhttp
  namespace: istio-system
spec:
  actions:
  - handler: handler.prometheus
    instances:
    - myrequestcount.metric
  match: context.protocol == "http" || context.protocol == "grpc"
