{
 "title": "evangelist-init",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Traffic Stats - All",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{source_app=~\"(mock|istio-ingress|istio-egress).*\", destination_app=~\"(mock|istio-ingress|istio-egress).*\", response_code=~\"2[0-9][0-9]\"}[30s])) by (source_version, destination_version, source_app, destination_app)",
     "legendFormat": "{{source_version}}.{{source_app}} -> {{destination_version}}.{{destination_app}}"
    }
   ]
  },
  {
   "title": "Latency Stats - All",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(istio_request_duration_seconds_bucket{source_app=~\"(mock|istio-ingress|istio-egress).*\", destination_app=~\"(mock|istio-ingress|istio-egress).*\", response_code=~\"2[0-9][0-9]\"}[30s])) by (le, source_app, source_version, destination_app, destination_version))",
     "legendFormat": "{{source_version}}.{{source_app}} -> {{destination_version}}.{{destination_app}}"
    }
   ]
  },
  {
   "title": "Traffic Stats by Source",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{source_app=~\"(mock|istio-ingress|istio-egress).*\", destination_app=~\"(mock|istio-ingress|istio-egress).*\", response_code=~\"2[0-9][0-9]\"}[30s])) by (source_version, source_app)",
     "legendFormat": "{{source_version}}.{{source_app}} -> "
    }
   ]
  },
  {
   "title": "Traffic Stats - by Destination",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{source_app=~\"(mock|istio-ingress|istio-egress).*\", destination_app=~\"(mock|istio-ingress|istio-egress).*\", response_code=~\"2[0-9][0-9]\"}[30s])) by (desntination_version, destination_app)",
     "legendFormat": "-> {{destination_version}}.{{destination_app}}"
    }
   ]
  }
 ]
}