apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mock-servers
  labels:
    tier: mock
spec:
  selector:
    matchLabels:
      tier: mock
  endpoints:
  - port: http1
    interval: 1s
