apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  annotations:
    "service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled": "true"
    "service.beta.kubernetes.io/aws-load-balancer-internal": "true"
  name: prometheus
  namespace: soa-mon
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    app: prometheus
