apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mock1
spec:
  hosts:
  - "mock.example.info"
  gateways:
  - soa-gateway
  http:
  - route:
    - destination:
        host: mock1-http1.soa-test.svc.cluster.local
        subset: v1
        port:
          number: 6000

---
apiVersion: "networking.istio.io/v1alpha3"
kind: DestinationRule
metadata:
  name: mock1
spec:
  host: "mock1-http1.soa-test.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
      loadBalancer:
        simple: LEAST_CONN
  - name: v2
    labels:
      version: v2
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
      loadBalancer:
        simple: LEAST_CONN
