apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mock1
spec:
  hosts:
  - "mock.example.info"
  gateways:
  - soa-gateway
  http:
  - route:
    - destination:
        host: mock1-authn.od-system.svc.cluster.local
        subset: v1
        port:
          number: 17001
